### ISSUE TITLE
Llama 3B models are Llama 3.2, not 3.1

### ISSUE THREAD

**Issue by philippgille** [ibm-granite/granite-3.0-language-models#1]
Hello 👋 , I noticed in the graphs you mention Llama-3.1-3B, but if I'm not mistaken the 3.1 family doesn't have a 3B version, only the 3.2 family has.

In your repo:
<img src="https://github.com/user-attachments/assets/7a0f9cd7-5769-4328-b4c9-2c8f7c5762b1" alt="screenshot" width="500"/>

While the 3.1 family model card only mentions the 8B, 70B and 405B: https://github.com/meta-llama/llama-models/blob/6940e562095c91ff322d8b7b4e460058ee94331c/models/llama3_1/MODEL_CARD.md

Only the 3.2 family lists a 3B model: https://github.com/meta-llama/llama-models/blob/6940e562095c91ff322d8b7b4e460058ee94331c/models/llama3_2/MODEL_CARD.md

**Comment by ameza13** [comment]
Thanks for bringing this up, we have fixed the typo.
